# Generated by Django 6.0.4 on 2026-04-16 10:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Child's display name (2-100 characters)",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        help_text="Age must be between 1 and 17",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(17),
                        ],
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key (e.g., 'avatars/uuid-xxxx/image-hash.jpg')",
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft delete flag - False hides profile but preserves history",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["parent", "is_active"], name="idx_parent_active"
                    ),
                    models.Index(fields=["created_at"], name="idx_child_created"),
                    models.Index(fields=["parent", "name"], name="idx_parent_name"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("parent", "name"),
                        name="unique_active_child_name_per_parent",
                    )
                ],
            },
        ),
    ]
